---
title: "Publicaciones"
author: "Pablo Rodríguez-Sánchez"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
  md_document:
    toc: false
    includes:
      in_header: headers/temp.md
---

```{r Setup, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE)
options(knitr.kable.NA = '')
```

```{r Dependencies, warning=FALSE, message=FALSE}
source('config.R')
source('auxs.R')

library(knitr)
library(dplyr)
library(ggplot2)
library(kableExtra)
library(readr)
library(sp)
```


```{r Load, warning=FALSE, message=FALSE}
key <- read_file('key.txt')
data <- get_data(key, save_backup = TRUE, ignore_future = TRUE)
```

```{r Filter, warning=FALSE}
data_table <- select(data, Date, Name, Type, Language)
```


## Artículos científicos

```{r Papers}
papers <- filter(data, Type == 'Paper')
papers <- select(papers, Date, NameURL, Author, Status, Publisher)

papers_num <- nrow(papers)
```

He sido autor o coautor en `r papers_num` artículos científicos:

```{r PapersTab}
kable(papers, format='markdown')
```

## Tesis doctoral
```{r thesis}
## My PhD thesis
theses <- filter(data, Type == 'Thesis' & (Role == 'Chapter author' | Role == 'Author'))
theses <- select(theses, Date, NameURL, Role, Institution)

theses_num <- nrow(theses)
```

```{r ThesisTab}
kable(theses, format='markdown')
```

## Libros

```{r Books}
## Books and book chapters
books <- filter(data, Type == 'Book' & (Role == 'Chapter author' | Role == 'Author'))
books <- select(books, Date, Name, Role, Institution)

books_num <- nrow(books)
```

He participado en la redacción de `r books_num` libro:

```{r BooksTab}
kable(books, format='markdown')
```

## Software científico
```{r Code}
code <- filter(data, Type == 'Code')
code <- select(code, Date, NameURL, Role, Language)

code_num <- nrow(code)
```

He publicado `r code_num` pequeños proyectos de software científico:

```{r CodeTab}
kable(code, format='markdown')
```

***

Built with R `r getRversion()` and RStudio.
