---
title: "Teaching"
author: "Pablo Rodríguez-Sánchez"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
  md_document:
    toc: false
    includes:
      in_header: headers/temp.md
---

```{r Setup, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE)
options(knitr.kable.NA = '')
```

```{r Dependencies, warning=FALSE, message=FALSE}
source('config.R')
source('auxs.R')

library(knitr)
library(dplyr)
library(ggplot2)
library(kableExtra)
library(readr)
library(sp)
```


```{r Load, warning=FALSE, message=FALSE}
key <- read_file('key.txt')
data <- get_data(key, save_backup = TRUE, ignore_future = TRUE)
```

```{r Filter, warning=FALSE}
data_table <- select(data, Date, Name, Type, Language)
```
## Teaching
```{r Classes}
classes <- filter(data, Type == 'Course' & (Role == 'Professor' | Role == 'Teaching assistant'))
classes <- select(classes, Date, End.date, NameURL, Role, Institution, Country)
classes <- mutate(classes, Country = get_flag(Country))

classes_num <- nrow(classes)
```

I've been involved in the teaching of `r classes_num` courses:

```{r ClassesTab}
kable(classes, format='pandoc')
```

***

Built with R `r getRversion()` and RStudio.
